'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetailDeposit
    Public Property Id As Integer
    Public Property IdDesposit As Integer
    Public Property IdService As Integer
    Public Property IdPrepaidPackage As Nullable(Of Integer)
    Public Property PriceUnit As Integer
    Public Property TotalUnit As Double
    Public Property CompletedDatetime As Nullable(Of Date)

    Public Overridable Property HeaderDeposit As HeaderDeposit
    Public Overridable Property PrepaidPackage As PrepaidPackage
    Public Overridable Property Service As Service

End Class
