'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PC_BE_MODUL2Entities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PC_BE_MODUL2Entities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property DetailDeposits() As DbSet(Of DetailDeposit)
    Public Overridable Property Employees() As DbSet(Of Employee)
    Public Overridable Property HeaderDeposits() As DbSet(Of HeaderDeposit)
    Public Overridable Property Jobs() As DbSet(Of Job)
    Public Overridable Property Packages() As DbSet(Of Package)
    Public Overridable Property PrepaidPackages() As DbSet(Of PrepaidPackage)
    Public Overridable Property Services() As DbSet(Of Service)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property Units() As DbSet(Of Unit)

End Class
