'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Package
    Public Property Id As Integer
    Public Property IdService As Integer
    Public Property TotalUnit As Integer
    Public Property Price As Integer

    Public Overridable Property Service As Service
    Public Overridable Property PrepaidPackages As ICollection(Of PrepaidPackage) = New HashSet(Of PrepaidPackage)

End Class
